apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: broker
  name: file-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi