# Default values for helm-proxy-v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  pullPolicy: Always
  tag: 1.0.0

deployment:
  name: txtextractor
  namespace: txtextractor
  containers:
    name: txtextractor

app:
  selector: txtextractor
  replicaCount: 1

config:
  name: txtextractor-config

service:
  name: txtextractor-service
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  name: broker-ingress
  labels: {}
  annotations: {
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  }
  hosts:
   []
   # - broker.example.com
  paths:
    - /broker
  extraPaths:
    []
    # - path: /*
    #   pathType: Prefix
    #   backend:
    #     service
    #       name: ssl-redirect
    #       port:
    #         name: use-annotation
