apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRole.name }}
  namespace: {{ .Values.deployment.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ .Values.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.deployment.namespace }}