apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    name: {{ .Values.config.name }}
  namespace: {{ .Values.deployment.namespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: {{ .Values.scrape.interval | default "2"}}s
      evaluation_interval: {{ .Values.scrape.interval | default "2"}}s
    scrape_configs:
    - job_name: {{ .Values.scrape.name }}
      static_configs:
      - targets: [{{ .Values.scrape.service }}.{{ .Values.scrape.namespace }}.svc.cluster.local:{{ .Values.scrape.port }}]
