apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '{{ .Values.deployment.containers.port }}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containers.port }}
  selector:
    app: {{ .Values.app.selector }}