apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  labels:
    name: {{ .Values.config.name }}
  namespace: {{ .Values.deployment.namespace }}
data:
  config.yaml: |
    logging:
      # 0 = NONE; 1 = INFO; 2 = WARNING; 3 = ERROR; 4 = DEBUG
      level: 3
      profiling: false

    metrics:
      export: true
      path: '/metrics'

    app:
      text_extractor_url: 'http://txtextractor-service.broker.svc.cluster.local'
      text_analyzer_url: 'http://analyzer-service.broker.svc.cluster.local'
      redis_url: 'http://redis-service.broker.svc.cluster.local:6379'
      raw_file_storage: '/tmp'
      task_queue_length: 10000

    server:
      address: ':8080'
      upload_path: '/broker/upload'
      adaptive_path: '/broker/adaptive'