apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: txtextractor-hpa
  namespace: broker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: txtextractor
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: queue-length
        selector: {
          matchLabels: {
            kubernetes_namespace: "broker",
          }
        }
      target:
        type: Value
        value: 0.05
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 # 30 secs
      policies:
      - type: Pods
        value: 2
        periodSeconds: 30 # wait 30 seconds before scaling down (2 by 2)
      selectPolicy: Min