rules:
  default: false
  external:
  - seriesQuery: '{__name__=~"broker_requests_waiting.*"}'
    resources:
      namespaced: false
      # overrides:
      #   kubernetes_namespace: {resource: "namespace"}
      #   kubernetes_pod_name: {resource: "pod"}
    name:
      matches: ""
      as: "queue-length"
    metricsQuery: sum(broker_requests_waiting{<<.LabelMatchers>>})

  - seriesQuery: 'broker_callers_running{kubernetes_namespace!="",kubernetes_pod_name!=""}'
    resources:
      namespaced: false
      # overrides:
      #   kubernetes_namespace: {resource: "namespace"}
      #   kubernetes_pod_name: {resource: "pod"}
    name:
      as: "queue-length-2"
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>})

prometheus:
  url: http://prometheus-service.prometheus.svc.cluster.local
  path: /prom
  port: 8080