rules:
  default: false
  external:
  - seriesQuery: '{__name__=~"broker_requests_waiting.*"}'
    resources:
      overrides:
        kubernetes_namespace:
          resource: namespace
        kubernetes_pod_name:
          resource: pod
    name:
      matches: "^(.*)"
      as: "queue-length"
    metricsQuery: sum(broker_requests_waiting{<<.LabelMatchers>>})
  - seriesQuery: '{__name__=~"broker_callers_running.*"}'
    resources:
      overrides:
        kubernetes_namespace:
          resource: namespace
        kubernetes_pod_name:
          resource: pod
    name:
      matches: "^(.*)"
      as: "queue-length-2"
    metricsQuery: sum(broker_callers_running{})

prometheus:
  url: http://prometheus-service.prometheus.svc.cluster.local
  port: 8080