# Default values for helm-proxy-v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  pullPolicy: Always
  tag: 1.0.8

deployment:
  name: broker
  namespace: broker
  containers:
    name: broker

app:
  selector: broker
  replicaCount: 3

config:
  name: broker-config

service:
  name: broker-service
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  name: broker-ingress
  labels: {}
  annotations: {
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  }
  hosts:
   []
   # - broker.example.com
  paths:
    - /broker/upload
    - /broker/adaptive
  extraPaths:
    []
    # - path: /*
    #   pathType: Prefix
    #   backend:
    #     service
    #       name: ssl-redirect
    #       port:
    #         name: use-annotation
